### ISSUE TITLE
Is it possible to make this package available in dart 2.18.2?

### ISSUE THREAD

**Issue by Dabbit-Chan** [bernaferrari/non_uniform_border#2]
There is a tricky ui problem that needs to be solved with this package, but I can't upgrade the dart version yet, so I would like to ask if this library can be used in a lower version of dart?

**Comment by bernaferrari** [comment]
I'm traveling right now, so the best possible way would be you copying and pasting my file into your project. There are no Dart 3 features yet.

**Comment by Dabbit-Chan** [comment]
`The getter 'strokeAlignInside' isn't defined for the type 'BorderSide'.`
Thank you, but here's a question. is BorderSide.strokeAlignInside only available in flutter 3.10? Have a nice travel!

**Comment by Dabbit-Chan** [comment]
> `The getter 'strokeAlignInside' isn't defined for the type 'BorderSide'.` Thank you, but here's a question. is BorderSide.strokeAlignInside only available in flutter 3.10? Have a nice travel!

Thanks a lot, I just set BorderSide.strokeAlignInside to -1 and it work!
